### ISSUE TITLE
Minimal Async Timer example crashes at runtime

### ISSUE THREAD

**Issue by Vollbrecht** [ivmarkov/ruwm#5]
Sorry if this is the wrong repository, i cant create an issue in your forked embassy repository. I distilled down your async timer example used in your keepalive worker. 

What should happen: Button pin activates the async timer. Async timer should await 2 seconds and as long not an other button is pressed it should wait again 2 seconds indefinitely. 
What happens: After the first run of `embassy_time::Timer::after(embassy_time::Duration::from_secs_floor(2))` directly after 2 seconds or any other given time the esp hard resets.

To corner and reproduce the problem i created a super minimal repository here  [unfixed commit](https://github.com/Vollbrecht/timer_test/tree/d95646b43400015b54fef738ec19f4f2d205f1ca) .
Its just the init for an 1 task executor and some boilerplate notification stuff. 

Since embassy uses defmt i dont know how to debug it really. I tried debugging it with openocd but i couldn't get a stacktrace after the reset happens. I dont think a panic happens in rtos rather somewhere in embassy. If you have any pointers how i could takle the problem or you could verify that your keepalive code works on your hardware that would be nice.

Anyway thanks for your really nice work here! Without it i wouldn't be so far as i am now!

**Comment by Vollbrecht** [comment]
when i dont let the timer run out pushing the button faster than the timer interval the either clause does what one expect.

**Comment by Vollbrecht** [comment]
after the reset i got the following
``` 
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x403812fa
SPIWP:0xee
``` 
` rst:0x3 (RTC_SW_SYS_RST) ` is this what caused the reset ?

**Comment by ivmarkov** [comment]
Can you pull latest `esp-idf-hal` and `esp-idf-svc` and try to recompile? The crash reported for esp32s3 is now fixed, so it might be working on the c3 as well now. Otherwise, I'll look through it over the weekend.

**Comment by Vollbrecht** [comment]
i updated the project and now using `esp_idf_hal::task::critical_section::link();` it fixes the problem now and work as expected ! 
still using `CONFIG_ESP_TIMER_SUPPORTS_ISR_DISPATCH_METHOD=y` & `CONFIG_ESP_EVENT_POST_FROM_ISR=y`

here is the  [running test case](https://github.com/Vollbrecht/timer_test/tree/e340b130afb4eb85dded3db1e2f6ed45d6acf68b)

thank you for fixing it :heart:
