### ISSUE TITLE
sending two ws frames back-to-back deadlocks

### ISSUE THREAD

**Issue by Vollbrecht** [ivmarkov/ruwm#8]
minimal test repo to confirm : https://github.com/Vollbrecht/minimal-ws-deadlock
the deadlock happens on send -> it only happens when the recv should send something. if two ws frames are send back-to-back and recv does not send it works. checkout README.md inside the testrepo

**Comment by ivmarkov** [comment]
With the new WS task, where the send and receive are completely separated, I don't think this happens anymore.
